print("Allow duplicate value in Tuple")
my_tuple = (1, 2, 3, 2, 4, 1, 5)
print(my_tuple)
Allow_duplicate_value = ("Vishal","haribhau","jagdhane","haribhau","Vishal","jagdhane","Aurangabad","Chatrpati Shmbahji Nagar","The city of Gates","The city of Gates")
print(Allow_duplicate_value)
print(type(Allow_duplicate_value))
# print (count:=Allow_duplicate_value.count("vishal"))
print(Allow_duplicate_value.count("Vishal"))
print(Allow_duplicate_value.__contains__("Vishal"))
print(len(Allow_duplicate_value))
